//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfTranslater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pdfTranslater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_multi {
            get {
                object obj = ResourceManager.GetObject("rsz_multi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translit!.
        /// </summary>
        internal static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fanyi.sogou.com/reventondc/microsoftGetSpeakFile?from=translateweb&amp;spokenDialect=en&amp;text=.
        /// </summary>
        internal static string SogouAudioUrl {
            get {
                return ResourceManager.GetString("SogouAudioUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from=auto&amp;to=zh-CHS&amp;client=pc&amp;fr=browser_pc&amp;useDetect=on&amp;useDetectResult=on&amp;needQc=1&amp;pid=sogou-dict-vr&amp;oxford=on&amp;isReturnSugg=on&amp;uuid=.
        /// </summary>
        internal static string SogouPostDataPrefix {
            get {
                return ResourceManager.GetString("SogouPostDataPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fanyi.sogou.com/reventondc/translate.
        /// </summary>
        internal static string SogouTranslaterUrl {
            get {
                return ResourceManager.GetString("SogouTranslaterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk.
        /// </summary>
        internal static string TranslitAboutUrl {
            get {
                return ResourceManager.GetString("TranslitAboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk/update/check?userid=.
        /// </summary>
        internal static string TranslitCheckUpdateUrl {
            get {
                return ResourceManager.GetString("TranslitCheckUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;version=18.11.
        /// </summary>
        internal static string TranslitCurrentVersion {
            get {
                return ResourceManager.GetString("TranslitCurrentVersion", resourceCulture);
            }
        }
    }
}
