//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfTranslater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pdfTranslater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {
        /// color:#333;
        /// background:#fff;
        /// -ms-text-size-adjust:100%;
        /// -webkit-text-size-adjust:100%;
        /// font-family:arial,pingfang sc,stheiti,Microsoft YaHei,sans-serif
        ///}
        ///body,dd,dl,form,h1,h2,h3,h4,h5,h6,ol,p,td,th,ul {
        /// margin:0;
        /// padding:0
        ///}
        ///button,input,select,textarea {
        /// font-size:100%;
        /// margin:0;
        /// vertical-align:baseline;
        /// *vertical-align:middle
        ///}
        ///input::-ms-clear,input::-ms-reveal {
        /// display:none
        ///}
        ///textarea {
        /// overflow:auto
        ///}
        ///table {
        /// border-collapse:collapse;
        /// border-spacing:0
        ///} [rest of string was truncated]&quot;;.
        /// </summary>
        public static string blue_stylesheet {
            get {
                return ResourceManager.GetString("blue_stylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon hiddenNotifyIcon {
            get {
                object obj = ResourceManager.GetObject("hiddenNotifyIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_close {
            get {
                object obj = ResourceManager.GetObject("mini_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_close_hover {
            get {
                object obj = ResourceManager.GetObject("mini_close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_down {
            get {
                object obj = ResourceManager.GetObject("mini_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_down_hover {
            get {
                object obj = ResourceManager.GetObject("mini_down_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_edit {
            get {
                object obj = ResourceManager.GetObject("mini_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_edit_hover {
            get {
                object obj = ResourceManager.GetObject("mini_edit_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok {
            get {
                object obj = ResourceManager.GetObject("mini_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_a {
            get {
                object obj = ResourceManager.GetObject("mini_ok_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_b {
            get {
                object obj = ResourceManager.GetObject("mini_ok_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_c {
            get {
                object obj = ResourceManager.GetObject("mini_ok_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_hover {
            get {
                object obj = ResourceManager.GetObject("mini_ok_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_y {
            get {
                object obj = ResourceManager.GetObject("mini_ok_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_ok_z {
            get {
                object obj = ResourceManager.GetObject("mini_ok_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_query {
            get {
                object obj = ResourceManager.GetObject("mini_query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_query_a {
            get {
                object obj = ResourceManager.GetObject("mini_query_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_query_b {
            get {
                object obj = ResourceManager.GetObject("mini_query_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_query_c {
            get {
                object obj = ResourceManager.GetObject("mini_query_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_query_hover {
            get {
                object obj = ResourceManager.GetObject("mini_query_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_sprig {
            get {
                object obj = ResourceManager.GetObject("mini_sprig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_sprig_down {
            get {
                object obj = ResourceManager.GetObject("mini_sprig_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_sprig_down_hover {
            get {
                object obj = ResourceManager.GetObject("mini_sprig_down_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_sprig_hover {
            get {
                object obj = ResourceManager.GetObject("mini_sprig_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_up {
            get {
                object obj = ResourceManager.GetObject("mini_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mini_up_hover {
            get {
                object obj = ResourceManager.GetObject("mini_up_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translit!.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fanyi.sogou.com/reventondc/microsoftGetSpeakFile?from=translateweb&amp;spokenDialect=en&amp;text=.
        /// </summary>
        public static string SogouAudioUrl {
            get {
                return ResourceManager.GetString("SogouAudioUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from=auto&amp;to=zh-CHS&amp;client=pc&amp;fr=browser_pc&amp;useDetect=on&amp;useDetectResult=on&amp;needQc=1&amp;pid=sogou-dict-vr&amp;oxford=on&amp;isReturnSugg=on&amp;uuid=.
        /// </summary>
        public static string SogouPostDataPrefix {
            get {
                return ResourceManager.GetString("SogouPostDataPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk/update/salt?userid=.
        /// </summary>
        public static string SogouSaltUrl {
            get {
                return ResourceManager.GetString("SogouSaltUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fanyi.sogou.com/reventondc/translateV1.
        /// </summary>
        public static string SogouTranslaterUrl {
            get {
                return ResourceManager.GetString("SogouTranslaterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon translit {
            get {
                object obj = ResourceManager.GetObject("translit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon translit_bw {
            get {
                object obj = ResourceManager.GetObject("translit_bw", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap translit_text_Logo {
            get {
                object obj = ResourceManager.GetObject("translit_text_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk/.
        /// </summary>
        public static string TranslitAboutUrl {
            get {
                return ResourceManager.GetString("TranslitAboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk/update/check?userid=.
        /// </summary>
        public static string TranslitCheckUpdateUrl {
            get {
                return ResourceManager.GetString("TranslitCheckUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.02.
        /// </summary>
        public static string TranslitCurrentVersion {
            get {
                return ResourceManager.GetString("TranslitCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.translit.tk/update/message?userid=.
        /// </summary>
        public static string TranslitMessageUrl {
            get {
                return ResourceManager.GetString("TranslitMessageUrl", resourceCulture);
            }
        }
    }
}
